version: '3'

services:
  db:
    image: postgres:alpine
    container_name: 'pgsql'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    env_file:
      - .env
